//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR.DbEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LD_kursEntities : DbContext
    {
        public LD_kursEntities()
            : base("name=LD_kursEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<designer> designer { get; set; }
        public virtual DbSet<difficulties> difficulties { get; set; }
        public virtual DbSet<land> land { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<work> work { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
    
        public virtual ObjectResult<GetOrderReport2_Result> GetOrderReport2(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderReport2_Result>("GetOrderReport2", idParameter);
        }
    
        public virtual ObjectResult<AvgOrderReportYear_Result> AvgOrderReportYear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AvgOrderReportYear_Result>("AvgOrderReportYear");
        }
    
        public virtual ObjectResult<AvgOrderReport_Result> AvgOrderReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AvgOrderReport_Result>("AvgOrderReport");
        }
    
        public virtual ObjectResult<AvgOrderReportMonth_Result> AvgOrderReportMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AvgOrderReportMonth_Result>("AvgOrderReportMonth");
        }
    }
}
