//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR.DbEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class work
    {
        public int id { get; set; }
        public string typee { get; set; }
        public int countt { get; set; }
        public int price { get; set; }
        public int zakazId { get; set; }
    
        public virtual zakaz zakaz { get; set; }
    }
}
